name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.0, 1.0.1, 2.0.0)'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Update version
        id: version
        run: |
          VERSION_INPUT="${{ github.event.inputs.version }}"

          # Validate version format
          if ! [[ "$VERSION_INPUT" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Invalid version format. Please use semantic versioning (e.g., 1.0.0)"
            exit 1
          fi

          # Update package.json version
          npm version $VERSION_INPUT --no-git-tag-version

          echo "new_version=$VERSION_INPUT" >> $GITHUB_OUTPUT

      - name: Create and publish from release branch
        run: |
          RELEASE_BRANCH="release-v${{ steps.version.outputs.new_version }}"
          git checkout -b $RELEASE_BRANCH
          git add package.json package-lock.json
          git commit -m "chore: release v${{ steps.version.outputs.new_version }}"
          git push origin $RELEASE_BRANCH

          # Create tag and publish to npm from release branch
          git tag v${{ steps.version.outputs.new_version }}
          git push origin v${{ steps.version.outputs.new_version }}

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.new_version }}
          release_name: Release v${{ steps.version.outputs.new_version }}
          body: |
            ## 🚀 Release v${{ steps.version.outputs.new_version }}

            ### ✅ Published to npm Registry

            Install with:
            ```bash
            npm install @marqeta/marqeta-mcp@${{ steps.version.outputs.new_version }}
            ```

            Or use with npx:
            ```bash
            npx @marqeta/marqeta-mcp@${{ steps.version.outputs.new_version }}
            ```
          draft: false
          prerelease: false

      - name: Create PR to main with version bump
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `chore: bump version to v${{ steps.version.outputs.new_version }}`,
              body: `## Version Bump to v${{ steps.version.outputs.new_version }}

            This PR updates the main branch with the version bump that was released.

            ### Changes:
            - Updated package.json version to ${{ steps.version.outputs.new_version }}
            - Updated package-lock.json

            ### Release Information:
            - ✅ Release published to npm
            - ✅ GitHub release created
            - ✅ Git tag created

            This PR requires manual approval and merge.`,
              head: 'release-v${{ steps.version.outputs.new_version }}',
              base: 'main'
            });

            console.log(`Created version bump PR #${pr.data.number}: ${pr.data.html_url}`);
